### ISSUE TITLE
Proxy node questions

### ISSUE THREAD

**Issue by rumyantseva** [chmod666org/scaleway-k8s#21]
Hi!
Thank you very much for [a great article](https://chmod666.org/2017/11/Hosting-a-self-made-Kubernetes-infrastructure-on-Scaleway).

I'm trying to go through the playbooks and I have a question here:
https://github.com/chmod666org/scaleway-k8s/blob/9ae853b178fb1f19ab9c2c461da29ba3a489ec62/k8s.yml#L69-L73

Could you help me to understand why do you install ingress, lego and kubernetes-dashboard on both `proxy` and `master` node types? Thank you in advance.

P.S. And the same question here:
https://github.com/chmod666org/scaleway-k8s/blob/9ae853b178fb1f19ab9c2c461da29ba3a489ec62/beforek8s.yml#L39-L42
Why do you need docker on `proxy` nodes?

**Comment by chmod666org** [comment]
Hi,

Thank you for your comment,

- Regarding the first question: the role ingress must run on masters and proxy. The kubernetes manifest is deployed using the kube ansible module, this one must be launched from the master node which is the only one to have a kubeconfig and the only one that can access the k8s api to deploy the ingress manifest. It is also run on proxy nodes because I have to deploy keepalived and some notify scripts on those nodes (to ensure ha). If you have a deeper look at the role you can see that some of the tasks runs on the master and other ones on the proxy nodes (check the when). For kubernetes-dashboard I should remove the task from the proxy ... but as there are some conditions the apply the tasks only the master ... this is not a problem too. Same problem for lego.
- The proxy nodes are kubernetes nodes which are labeled to only run the ingress-controller. Docker must be installed because they are kubernetes nodes too.

Hope it helps.

**Comment by rumyantseva** [comment]
Thank you very much! I think, now I understand the idea, yeah! 👍
